[{
	"metadata": [{

			"event-pattern": "condition status updated",
			"event-rule": "kanan-condition-status-updated-to-iics-{env}",
			"id": "1",
			"param-1": "json_data[\"detail\"]['loan_id']",
			"param-2": "",
			"param-3": "",
			"param-4": "",
			"param-count": 1,
			"secretname": "{0}/correspondent/iics-sa-dw",
			"sqs": "kanan-hubs-events-framework",
			"process_name":"stipDetails",
			"tgt-url": "https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/p_API_ssvr_Loan_Stipdetails_Mailroom",
			"tgt-url-parameter": "\"LoanGuid\":\"{0}\""

		}, {
			"event-pattern": "condition created",
			"event-rule": "kanan-enhanced-condition-created-to-iics-{env}",
			"id": "2",
			"param-1": "json_data[\"detail\"]['loan_id']",
			"param-2": "",
			"param-3": "",
			"param-4": "",
			"param-count": 1,
			"secretname": "{0}/correspondent/iics-sa-dw",
			"sqs": "kanan-hubs-events-framework",
			"process_name":"stipDetails",
			"tgt-url": "https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/p_API_ssvr_Loan_Stipdetails_Mailroom",
			"tgt-url-parameter": "\"LoanGuid\":\"{0}\""
		}, {
			"event-pattern": "condition updated",
			"event-rule": "kanan-enhanced-condition-updated-to-iics-{env}",
			"id": "3",
			"param-1": "json_data[\"detail\"]['loan_id']",
			"param-2": "",
			"param-3": "",
			"param-4": "",
			"param-count": 1,
			"secretname": "{0}/correspondent/iics-sa-dw",
			"sqs": "kanan-hubs-events-framework",
			"process_name":"stipDetails",
			"tgt-url": "https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/p_API_ssvr_Loan_Stipdetails_Mailroom",
			"tgt-url-parameter": "\"LoanGuid\":\"{0}\""
		},
		{
			"event-pattern": "trade created",
			"event-rule": "kanan-hubs-trade-created-to-iics-{env}",
			"id": "4",
			"param-1": "json_data[\"detail\"][\"trade_id\"]",
			"param-2": "",
			"param-3": "",
			"param-4": "",
			"param-count": 1,
			"secretname": "{0}/correspondent/iics-sa-dw",
			"sqs": "kanan-hubs-events-framework",
			"process_name":"Trade",
			"tgt-url": "https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/p_API_SSVR_getTradeDetails_Mailroom",
			"tgt-url-parameter": "\"tradeId\":\"{0}\""
		},
		{
			"event-pattern": "trade updated",
			"event-rule": "kanan-hubs-trade-updated-to-iics-{env}",
			"id": "5",
			"param-1": "json_data[\"detail\"]['trade_id']",
			"param-2": "",
			"param-3": "",
			"param-4": "",
			"param-count": 1,
			"secretname": "{0}/correspondent/iics-sa-dw",
			"sqs": "kanan-hubs-events-framework",
			"process_name":"Trade",
			"tgt-url": "https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/p_API_SSVR_getTradeDetails_Mailroom",
			"tgt-url-parameter": "\"tradeId\":\"{0}\""
		},
		{
			"event-pattern": "trade published",
			"event-rule": "kanan-hubs-trade-published-to-iics-{env}",
			"id": "6",
			"param-1": "json_data[\"detail\"]['trade_id']",
			"param-2": "",
			"param-3": "",
			"param-4": "",
			"param-count": 1,
			"secretname": "{0}/correspondent/iics-sa-dw",
			"sqs": "kanan-hubs-events-framework",
			"process_name":"Trade",
			"tgt-url": "https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/p_API_SSVR_getTradeDetails_Mailroom",
			"tgt-url-parameter": "\"tradeId\":\"{0}\""
		},
		{
			"event-pattern": "Package Processing Completed",
			"event-rule": "kanan-hubs-package-processing-completed-to-iics-{env}",
			"id": "7",
			"param-1": "json_data[\"detail\"]['loan_id']",
			"param-2": "json_data[\"detail\"]['location']['bucket']",
			"param-3": "json_data[\"detail\"]['location']['xml_key']",
			"param-4": "json_data[\"detail\"]['location']['xml_meta_key']",
			"param-count": 4,
			"secretname": "{0}/correspondent/iics-sa-dw",
			"sqs": "kanan-hubs-events-framework",
			"process_name":"LoanLogics",
			"tgt-url": "https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/p_loan_logics_mailroom",
			"tgt-url-parameter": "\"loan_id\":\"{0}\",\"bucket\": \"{1}\",\"xml_key\": \"{2}\", \"xml_meta_key\": \"{3}\""
		},
		{
			"event-pattern": "message uploaded",
			"event-rule": "kanan-hubs-message-uploaded-to-iics-{env}",
			"id": "8",
			"param-1": "json_data[\"detail\"]['loan_id']",
			"param-2": "o_env",
			"param-3": "",
			"param-4": "",
			"param-count": 3,
			"secretname": "{0}/correspondent/iics-sa-dw",
			"sqs": "kanan-hubs-events-framework",
			"process_name":"desktop underwriter",
			"tgt-url": "https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/p_desktop_underwriter_mailroom",
			"tgt-url-parameter": "\"loan_id\":\"{0}\",\"bucket\": \"kanan-tpi-object-store-{1}\",\"json_key\": \"archive/{0}/du-messages/du_messages.json\""
		},
		{
			"event-pattern": "external organization created",
			"event-rule": "kanan-hubs-external-organization-created-to-iics-{env}",
			"id": "9",
			"param-1": "json_data[\"detail\"]['external_org_id']",
			"param-2": "",
			"param-3": "",
			"param-4": "",
			"param-count": "1",
			"secretname": "{0}/correspondent/iics-sa-dw",
			"sqs": "kanan-hubs-events-framework",
			"process_name":"ClientConfig",
			"tgt-url": "https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/p_ssvr_ClientConfig_Mailroom",
			"tgt-url-parameter": "\"orgId\":\"{0}\""
		},
		{
			"event-pattern": "external organization updated",
			"event-rule": "kanan-hubs-external-organization-updated-to-iics-{env}",
			"id": "10",
			"param-1": "json_data[\"detail\"]['external_org_id']",
			"param-2": "",
			"param-3": "",
			"param-4": "",
			"param-count": "1",
			"secretname": "{0}/correspondent/iics-sa-dw",
			"sqs": "kanan-hubs-events-framework",
			"process_name":"ClientConfig",
			"tgt-url": "https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/p_ssvr_ClientConfig_Mailroom",
			"tgt-url-parameter": "\"orgId\":\"{0}\""
		}

	]
}]